2022-12-06 11:14:01,365 ERROR: Exception on /login [POST] [in D:\projects\microblog\mb\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\microblog\mb\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\app\routes.py", line 46, in login
    user = User.query.filter_by(username=form.username.data).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\orm\query.py", line 2823, in first
    return self.limit(1)._iter().first()
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\orm\query.py", line 2915, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\orm\session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\sql\elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\util\compat.py", line 210, in raise_
    raise exception
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "D:\projects\microblog\mb\Lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('eric', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-12-06 11:14:09,572 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:37]
2022-12-06 11:15:57,145 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:37]
2022-12-06 11:17:52,798 INFO: Microblog startup [in D:\projects\microblog\app\__init__.py:37]
2022-12-06 11:21:22,091 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 11:47:02,128 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 11:52:23,943 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 11:52:53,737 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 11:53:31,864 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 11:54:03,294 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:00:58,853 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:15:17,700 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:15:29,280 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:24:47,244 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:28:06,838 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:28:46,164 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:29:12,802 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:34:10,752 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:34:54,485 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:39:48,762 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:40:46,402 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
2022-12-06 13:45:43,181 INFO: Microblog startup [in d:\projects\microblog\app\__init__.py:37]
